version: '3.8'
services:
  db:
    image: postgres:14
    container_name: mmi_db
    environment:
      POSTGRES_USER: mmi
      POSTGRES_PASSWORD: pass
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U mmi" ]
      interval: 10s
      timeout: 5s
      retries: 5

  modmailinternal:
    build: .
    container_name: modmailinternal
    volumes:
      - ./data:/data

    depends_on:
      db:
        condition: service_healthy
